/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/router';
import * as i2 from '@angular/common';
import * as i3 from './app.component';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(16777216,(null as any),(null as any),1,'router-outlet',
      ([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
      i0.ɵdid(212992,(null as any),0,i1.RouterOutlet,[i1.ChildrenOutletContexts,i0.ViewContainerRef,
          i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],(null as any),
          (null as any)),(_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),22,'ul',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),5,'li',([] as any[]),
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted((null as any),['\n        '])),(_l()(),i0.ɵeld(0,(null as any),
          (null as any),2,'a',[['routerLink','/songs/users']],[[1,'target',0],[8,'href',
              4]],[[(null as any),'click']],(_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,8).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i0.ɵted((null as any),['Users'])),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵeld(0,
          (null as any),(null as any),5,'li',([] as any[]),(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink',
          '/songs/New-Releases']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],
          (_v,en,$event) => {
            var ad:boolean = true;
            if (('click' === en)) {
              const pd_0:any = ((<any>i0.ɵnov(_v,15).onClick($event.button,$event.ctrlKey,
                  $event.metaKey,$event.shiftKey)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i0.ɵted((null as any),['New Releases'])),(_l()(),
          i0.ɵted((null as any),['\n    '])),(_l()(),i0.ɵted((null as any),['\n    '])),
      (_l()(),i0.ɵeld(0,(null as any),(null as any),5,'li',([] as any[]),(null as any),
          (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
          ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'a',[['routerLink',
          '/songs']],[[1,'target',0],[8,'href',4]],[[(null as any),'click']],(_v,en,
          $event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i0.ɵnov(_v,22).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i0.ɵdid(671744,(null as any),0,i1.RouterLinkWithHref,
          [i1.Router,i1.ActivatedRoute,i2.LocationStrategy],{routerLink:[0,'routerLink']},
          (null as any)),(_l()(),i0.ɵted((null as any),['Songs'])),(_l()(),i0.ɵted((null as any),
          ['\n    '])),(_l()(),i0.ɵted((null as any),['\n']))],(_ck,_v) => {
    _ck(_v,1,0);
    const currVal_2:any = '/songs/users';
    _ck(_v,8,0,currVal_2);
    const currVal_5:any = '/songs/New-Releases';
    _ck(_v,15,0,currVal_5);
    const currVal_8:any = '/songs';
    _ck(_v,22,0,currVal_8);
  },(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,8).target;
    const currVal_1:any = i0.ɵnov(_v,8).href;
    _ck(_v,7,0,currVal_0,currVal_1);
    const currVal_3:any = i0.ɵnov(_v,15).target;
    const currVal_4:any = i0.ɵnov(_v,15).href;
    _ck(_v,14,0,currVal_3,currVal_4);
    const currVal_6:any = i0.ɵnov(_v,22).target;
    const currVal_7:any = i0.ɵnov(_v,22).href;
    _ck(_v,21,0,currVal_6,currVal_7);
  });
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i3.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i3.AppComponent> = i0.ɵccf('app',
    i3.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvY29tcG9uZW50cy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9JOi9Bbmd1bGFyVW5pdmVyc2FsL0FuZ3VsYXJVbml2ZXJzYWwvU2NyaXB0cy9hbmd1bGFyL2FwcC9jb21wb25lbnRzL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvY29tcG9uZW50cy9hcHAvdGVtcGxhdGUuaHRtbCIsIm5nOi8vL0k6L0FuZ3VsYXJVbml2ZXJzYWwvQW5ndWxhclVuaXZlcnNhbC9TY3JpcHRzL2FuZ3VsYXIvYXBwL2NvbXBvbmVudHMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPHJvdXRlci1vdXRsZXQ+PC9yb3V0ZXItb3V0bGV0PlxuPHVsPlxuICAgIDxsaT5cbiAgICAgICAgPGEgcm91dGVyTGluaz1cIi9zb25ncy91c2Vyc1wiPlVzZXJzPC9hPlxuICAgIDwvbGk+XG4gICAgPGxpPlxuICAgICAgICA8YSByb3V0ZXJMaW5rPVwiL3NvbmdzL05ldy1SZWxlYXNlc1wiPk5ldyBSZWxlYXNlczwvYT5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgICAgPGEgcm91dGVyTGluaz1cIi9zb25nc1wiPlNvbmdzPC9hPlxuICAgIDwvbGk+XG48L3VsPiIsIjxhcHA+PC9hcHA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBO2FBQUE7c0NBQUE7VUFBQSxlQUErQix1Q0FDL0I7VUFBQTtVQUFBLDRDQUFJO1VBQUEsYUFDQTtVQUFBO01BQUksK0NBQ0E7VUFBQTtjQUFBO1lBQUE7WUFBQTtjQUFBO2tCQUFBO2NBQUE7WUFBQTtZQUFBO1VBQUEsdUNBQUE7VUFBQTtVQUFBLGVBQTZCLDBDQUFTO1VBQUEsYUFDckMsMkNBQ0w7VUFBQTtVQUFBLDRDQUFJO1VBQUEsaUJBQ0E7VUFBQTtVQUFBO1lBQUE7WUFBQTtjQUFBO2tCQUFBO2NBQUE7WUFBQTtZQUFBO1VBQUEsdUNBQUE7VUFBQTtVQUFBLGVBQW9DLGlEQUFnQjtpQkFBQSw0QkFDbkQ7TUFDTDtVQUFBLDBEQUFJO1VBQUEsaUJBQ0E7VUFBQTtnQkFBQTtRQUFBO1FBQUE7VUFBQTtjQUFBO1VBQUE7UUFBQTtRQUFBO01BQUEsdUNBQUE7VUFBQTtVQUFBLGVBQXVCLDBDQUFTO1VBQUEsYUFDL0I7SUFWVDtJQUdXO0lBQUgsV0FBRyxTQUFIO0lBR0c7SUFBSCxZQUFHLFNBQUg7SUFHRztJQUFILFlBQUcsU0FBSDs7SUFOQTtJQUFBO0lBQUEsV0FBQSxtQkFBQTtJQUdBO0lBQUE7SUFBQSxZQUFBLG1CQUFBO0lBR0E7SUFBQTtJQUFBLFlBQUEsbUJBQUE7Ozs7b0JDVFI7TUFBQTthQUFBOzs7OyJ9
