/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './about.component';
const styles_AboutComponent:any[] = ([] as any[]);
export const RenderType_AboutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_AboutComponent,data:{}});
export function View_AboutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['Users']))],(null as any),(null as any));
}
export function View_AboutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'about',([] as any[]),
      (null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent)),
      i0.ɵdid(49152,(null as any),0,i1.AboutComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const AboutComponentNgFactory:i0.ComponentFactory<i1.AboutComponent> = i0.ɵccf('about',
    i1.AboutComponent,View_AboutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvY29tcG9uZW50cy9hYm91dC9hYm91dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvY29tcG9uZW50cy9hYm91dC9hYm91dC5jb21wb25lbnQudHMiLCJuZzovLy9JOi9Bbmd1bGFyVW5pdmVyc2FsL0FuZ3VsYXJVbml2ZXJzYWwvU2NyaXB0cy9hbmd1bGFyL2FwcC9jb21wb25lbnRzL2Fib3V0L3RlbXBsYXRlLmh0bWwiLCJuZzovLy9JOi9Bbmd1bGFyVW5pdmVyc2FsL0FuZ3VsYXJVbml2ZXJzYWwvU2NyaXB0cy9hbmd1bGFyL2FwcC9jb21wb25lbnRzL2Fib3V0L2Fib3V0LmNvbXBvbmVudC50cy5BYm91dENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5Vc2VyczwvaDE+IiwiPGFib3V0PjwvYWJvdXQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTthQUFBO1VBQUE7OzsifQ==
