/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.server.module';
import * as i2 from './components/about/about.component.ngfactory';
import * as i3 from './components/contact/contact.component.ngfactory';
import * as i4 from './components/home/home.component.ngfactory';
import * as i5 from './components/notfound/notfound.component.ngfactory';
import * as i6 from '@angular/common';
import * as i7 from '@angular/platform-browser';
import * as i8 from '@angular/http';
import * as i9 from '@angular/platform-server';
import * as i10 from '@angular/common/http';
import * as i11 from '@angular/animations';
import * as i12 from '@angular/platform-browser/animations';
import * as i13 from '@ngx-universal/state-transfer/src/http-transfer.service';
import * as i14 from '@ngx-universal/state-transfer/src/state-transfer.service';
import * as i15 from '@angular/router';
import * as i16 from '@ngx-universal/state-transfer/index';
import * as i17 from './components/about/about.component';
import * as i18 from './components/contact/contact.component';
import * as i19 from './components/home/home.component';
import * as i20 from './components/notfound/notfound.component';
import * as i21 from './app.module';
import * as i22 from '@ngx-universal/state-transfer/src/server-state-transfer.service';
import * as i23 from '@angular/animations/browser';
export const AppServerModuleNgFactory:i0.NgModuleFactory<i1.AppServerModule> = i0.ɵcmf(i1.AppServerModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.AboutComponentNgFactory,i3.ContactComponentNgFactory,i4.HomeComponentNgFactory,
              i5.NotFoundComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i6.NgLocalization,
              i6.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.IterableDiffers,
              i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i7.DomSanitizer,i7.ɵe,[i6.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i7.DomSanitizer]),i0.ɵmpd(4608,i7.HAMMER_GESTURE_CONFIG,
              i7.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i7.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i7.ɵDomEventsPlugin(p0_0),new i7.ɵKeyEventsPlugin(p1_0),
                    new i7.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i6.DOCUMENT,i6.DOCUMENT,i6.DOCUMENT,i7.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i7.EventManager,i7.EventManager,[i7.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i7.ɵDomSharedStylesHost,i7.ɵDomSharedStylesHost,[i6.DOCUMENT]),
          i0.ɵmpd(4608,i7.ɵDomRendererFactory2,i7.ɵDomRendererFactory2,[i7.EventManager,
              i7.ɵDomSharedStylesHost]),i0.ɵmpd(4352,i0.Testability,(null as any),
              ([] as any[])),i0.ɵmpd(4608,i7.Meta,i7.Meta,[i6.DOCUMENT]),i0.ɵmpd(4608,
              i7.Title,i7.Title,[i6.DOCUMENT]),i0.ɵmpd(4608,i8.BrowserXhr,i9.ɵc,([] as any[])),
          i0.ɵmpd(4608,i8.ResponseOptions,i8.BaseResponseOptions,([] as any[])),i0.ɵmpd(4608,
              i8.XSRFStrategy,i9.ɵd,([] as any[])),i0.ɵmpd(4608,i8.XHRBackend,i8.XHRBackend,
              [i8.BrowserXhr,i8.ResponseOptions,i8.XSRFStrategy]),i0.ɵmpd(4608,i8.RequestOptions,
              i8.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i8.Http,i9.ɵe,[i8.XHRBackend,
              i8.RequestOptions]),i0.ɵmpd(4608,i10.HttpXsrfTokenExtractor,i10.ɵg,[i6.DOCUMENT,
              i0.PLATFORM_ID,i10.ɵe]),i0.ɵmpd(4608,i10.ɵh,i10.ɵh,[i10.HttpXsrfTokenExtractor,
              i10.ɵf]),i0.ɵmpd(5120,i10.HTTP_INTERCEPTORS,(p0_0:any) => {
            return [p0_0];
          },[i10.ɵh]),i0.ɵmpd(4608,i10.XhrFactory,i9.ɵc,([] as any[])),i0.ɵmpd(4608,
              i10.HttpXhrBackend,i10.HttpXhrBackend,[i10.XhrFactory]),i0.ɵmpd(6144,
              i10.HttpBackend,(null as any),[i10.HttpXhrBackend]),i0.ɵmpd(5120,i10.HttpHandler,
              i9.ɵf,[i10.HttpBackend,[2,i10.HTTP_INTERCEPTORS]]),i0.ɵmpd(4608,i10.HttpClient,
              i10.HttpClient,[i10.HttpHandler]),i0.ɵmpd(4608,i10.ɵd,i10.ɵd,([] as any[])),
          i0.ɵmpd(4608,i11.AnimationBuilder,i12.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(4608,i13.HttpTransferService,i13.HttpTransferService,[i8.Http,i14.StateTransferService]),
          i0.ɵmpd(5120,i15.ActivatedRoute,i15.ɵf,[i15.Router]),i0.ɵmpd(4608,i15.NoPreloading,
              i15.NoPreloading,([] as any[])),i0.ɵmpd(6144,i15.PreloadingStrategy,
              (null as any),[i15.NoPreloading]),i0.ɵmpd(135680,i15.RouterPreloader,
              i15.RouterPreloader,[i15.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i15.PreloadingStrategy]),i0.ɵmpd(4608,i15.PreloadAllModules,
              i15.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i15.ROUTER_INITIALIZER,
              i15.ɵi,[i15.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i15.ROUTER_INITIALIZER]),i0.ɵmpd(512,i6.CommonModule,i6.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i7.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i15.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i15.ɵg,i15.ɵg,[i0.Injector]),i0.ɵmpd(256,
              i0.APP_ID,'my-app-id',([] as any[])),i0.ɵmpd(2048,i7.ɵTRANSITION_ID,
              (null as any),[i0.APP_ID]),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,
              p0_1:any,p1_0:any,p2_0:any,p2_1:any,p2_2:any) => {
            return [i7.ɵc(p0_0,p0_1),i15.ɵh(p1_0),i7.ɵf(p2_0,p2_1,p2_2)];
          },[[2,i7.NgProbeToken],[2,i0.NgProbeToken],i15.ɵg,i7.ɵTRANSITION_ID,i6.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i7.BrowserModule,
              i7.BrowserModule,[[3,i7.BrowserModule]]),i0.ɵmpd(512,i8.HttpModule,i8.HttpModule,
              ([] as any[])),i0.ɵmpd(512,i10.HttpClientXsrfModule,i10.HttpClientXsrfModule,
              ([] as any[])),i0.ɵmpd(512,i10.HttpClientModule,i10.HttpClientModule,
              ([] as any[])),i0.ɵmpd(512,i12.NoopAnimationsModule,i12.NoopAnimationsModule,
              ([] as any[])),i0.ɵmpd(512,i9.ServerModule,i9.ServerModule,([] as any[])),
          i0.ɵmpd(512,i16.ServerStateTransferModule,i16.ServerStateTransferModule,
              [[3,i16.ServerStateTransferModule]]),i0.ɵmpd(1024,i15.ɵa,i15.ɵd,[[3,
              i15.Router]]),i0.ɵmpd(512,i15.UrlSerializer,i15.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i15.ChildrenOutletContexts,i15.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i15.ROUTER_CONFIGURATION,{enableTracing:true},
              ([] as any[])),i0.ɵmpd(1024,i6.LocationStrategy,i15.ɵc,[i6.PlatformLocation,
              [2,i6.APP_BASE_HREF],i15.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i6.Location,
              i6.Location,[i6.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i15.ROUTES,
              () => {
                return [[{path:'songs/users',component:i17.AboutComponent},{path:'songs/New-Releases',
                    component:i18.ContactComponent},{path:'songs',component:i19.HomeComponent},
                    {path:'**',component:i20.NotFoundComponent}]];
              },([] as any[])),i0.ɵmpd(1024,i15.Router,i15.ɵe,[i0.ApplicationRef,i15.UrlSerializer,
              i15.ChildrenOutletContexts,i6.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i15.ROUTES,i15.ROUTER_CONFIGURATION,[2,i15.UrlHandlingStrategy],
              [2,i15.RouteReuseStrategy]]),i0.ɵmpd(512,i15.RouterModule,i15.RouterModule,
              [[2,i15.ɵa],[2,i15.Router]]),i0.ɵmpd(512,i16.HttpTransferModule,i16.HttpTransferModule,
              [[3,i16.HttpTransferModule]]),i0.ɵmpd(512,i21.AppModule,i21.AppModule,
              ([] as any[])),i0.ɵmpd(256,i22.STATE_ID,'STATE',([] as any[])),i0.ɵmpd(512,
              i9.ɵb,i9.ɵb,[i7.DOCUMENT,[2,i7.ɵTRANSITION_ID]]),i0.ɵmpd(2048,i7.ɵSharedStylesHost,
              (null as any),[i9.ɵb]),i0.ɵmpd(512,i9.ɵServerRendererFactory2,i9.ɵServerRendererFactory2,
              [i0.NgZone,i7.DOCUMENT,i7.ɵSharedStylesHost]),i0.ɵmpd(512,i23.AnimationDriver,
              i23.ɵNoopAnimationDriver,([] as any[])),i0.ɵmpd(1024,i23.ɵAnimationStyleNormalizer,
              i12.ɵd,([] as any[])),i0.ɵmpd(512,i23.ɵAnimationEngine,i12.ɵb,[i23.AnimationDriver,
              i23.ɵAnimationStyleNormalizer]),i0.ɵmpd(1024,i0.RendererFactory2,i9.ɵa,
              [i9.ɵServerRendererFactory2,i23.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(512,
              i14.StateTransferService,i22.ServerStateTransferService,[i22.STATE_ID,
                  i9.PlatformState,i0.RendererFactory2]),i0.ɵmpd(512,i1.AppServerModule,
              i1.AppServerModule,[i14.StateTransferService]),i0.ɵmpd(256,i10.ɵe,'XSRF-TOKEN',
              ([] as any[])),i0.ɵmpd(256,i10.ɵf,'X-XSRF-TOKEN',([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvYXBwLnNlcnZlci5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvYXBwLnNlcnZlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
