/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './notfound.component';
const styles_NotFoundComponent:any[] = ([] as any[]);
export const RenderType_NotFoundComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_NotFoundComponent,data:{}});
export function View_NotFoundComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['Not Found']))],(null as any),(null as any));
}
export function View_NotFoundComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'not-found',([] as any[]),
      (null as any),(null as any),(null as any),View_NotFoundComponent_0,RenderType_NotFoundComponent)),
      i0.ɵdid(49152,(null as any),0,i1.NotFoundComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const NotFoundComponentNgFactory:i0.ComponentFactory<i1.NotFoundComponent> = i0.ɵccf('not-found',
    i1.NotFoundComponent,View_NotFoundComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvY29tcG9uZW50cy9ub3Rmb3VuZC9ub3Rmb3VuZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvY29tcG9uZW50cy9ub3Rmb3VuZC9ub3Rmb3VuZC5jb21wb25lbnQudHMiLCJuZzovLy9JOi9Bbmd1bGFyVW5pdmVyc2FsL0FuZ3VsYXJVbml2ZXJzYWwvU2NyaXB0cy9hbmd1bGFyL2FwcC9jb21wb25lbnRzL25vdGZvdW5kL3RlbXBsYXRlLmh0bWwiLCJuZzovLy9JOi9Bbmd1bGFyVW5pdmVyc2FsL0FuZ3VsYXJVbml2ZXJzYWwvU2NyaXB0cy9hbmd1bGFyL2FwcC9jb21wb25lbnRzL25vdGZvdW5kL25vdGZvdW5kLmNvbXBvbmVudC50cy5Ob3RGb3VuZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5Ob3QgRm91bmQ8L2gxPiIsIjxub3QtZm91bmQ+PC9ub3QtZm91bmQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTthQUFBO1VBQUE7OzsifQ==
