/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './contact.component';
const styles_ContactComponent:any[] = ([] as any[]);
export const RenderType_ContactComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ContactComponent,data:{}});
export function View_ContactComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['New Releases']))],(null as any),(null as any));
}
export function View_ContactComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'contact',([] as any[]),
      (null as any),(null as any),(null as any),View_ContactComponent_0,RenderType_ContactComponent)),
      i0.ɵdid(49152,(null as any),0,i1.ContactComponent,([] as any[]),(null as any),
          (null as any))],(null as any),(null as any));
}
export const ContactComponentNgFactory:i0.ComponentFactory<i1.ContactComponent> = i0.ɵccf('contact',
    i1.ContactComponent,View_ContactComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvY29tcG9uZW50cy9jb250YWN0L2NvbnRhY3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0k6L0FuZ3VsYXJVbml2ZXJzYWwvQW5ndWxhclVuaXZlcnNhbC9TY3JpcHRzL2FuZ3VsYXIvYXBwL2NvbXBvbmVudHMvY29udGFjdC9jb250YWN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0k6L0FuZ3VsYXJVbml2ZXJzYWwvQW5ndWxhclVuaXZlcnNhbC9TY3JpcHRzL2FuZ3VsYXIvYXBwL2NvbXBvbmVudHMvY29udGFjdC90ZW1wbGF0ZS5odG1sIiwibmc6Ly8vSTovQW5ndWxhclVuaXZlcnNhbC9Bbmd1bGFyVW5pdmVyc2FsL1NjcmlwdHMvYW5ndWxhci9hcHAvY29tcG9uZW50cy9jb250YWN0L2NvbnRhY3QuY29tcG9uZW50LnRzLkNvbnRhY3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+TmV3IFJlbGVhc2VzPC9oMT4iLCI8Y29udGFjdD48L2NvbnRhY3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTthQUFBO1VBQUE7OzsifQ==
